/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AuthenticatedVisualTestsRouteImport } from './routes/_authenticated/visual-tests'
import { Route as AuthenticatedTestOrchestratorRouteImport } from './routes/_authenticated/test-orchestrator'
import { Route as AuthenticatedTestHubRouteImport } from './routes/_authenticated/test-hub'
import { Route as AuthenticatedTestDataRouteImport } from './routes/_authenticated/test-data'
import { Route as AuthenticatedTestCasesRouteImport } from './routes/_authenticated/test-cases'
import { Route as AuthenticatedSpeedLabRouteImport } from './routes/_authenticated/speed-lab'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedRecorderRouteImport } from './routes/_authenticated/recorder'
import { Route as AuthenticatedIdeRouteImport } from './routes/_authenticated/ide'
import { Route as AuthenticatedHttpLabRouteImport } from './routes/_authenticated/http-lab'
import { Route as AuthenticatedFlowBuilderRouteImport } from './routes/_authenticated/flow-builder'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBugsRouteImport } from './routes/_authenticated/bugs'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsProjectsRouteImport } from './routes/_authenticated/settings/projects'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsGitRouteImport } from './routes/_authenticated/settings/git'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedVisualTestsRoute =
  AuthenticatedVisualTestsRouteImport.update({
    id: '/visual-tests',
    path: '/visual-tests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTestOrchestratorRoute =
  AuthenticatedTestOrchestratorRouteImport.update({
    id: '/test-orchestrator',
    path: '/test-orchestrator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTestHubRoute = AuthenticatedTestHubRouteImport.update({
  id: '/test-hub',
  path: '/test-hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestDataRoute = AuthenticatedTestDataRouteImport.update({
  id: '/test-data',
  path: '/test-data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestCasesRoute = AuthenticatedTestCasesRouteImport.update({
  id: '/test-cases',
  path: '/test-cases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpeedLabRoute = AuthenticatedSpeedLabRouteImport.update({
  id: '/speed-lab',
  path: '/speed-lab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecorderRoute = AuthenticatedRecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdeRoute = AuthenticatedIdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHttpLabRoute = AuthenticatedHttpLabRouteImport.update({
  id: '/http-lab',
  path: '/http-lab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlowBuilderRoute =
  AuthenticatedFlowBuilderRouteImport.update({
    id: '/flow-builder',
    path: '/flow-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBugsRoute = AuthenticatedBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProjectsRoute =
  AuthenticatedSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGitRoute =
  AuthenticatedSettingsGitRouteImport.update({
    id: '/git',
    path: '/git',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRoute,
} as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/bugs': typeof AuthenticatedBugsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/flow-builder': typeof AuthenticatedFlowBuilderRoute
  '/http-lab': typeof AuthenticatedHttpLabRoute
  '/ide': typeof AuthenticatedIdeRoute
  '/recorder': typeof AuthenticatedRecorderRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/speed-lab': typeof AuthenticatedSpeedLabRoute
  '/test-cases': typeof AuthenticatedTestCasesRoute
  '/test-data': typeof AuthenticatedTestDataRoute
  '/test-hub': typeof AuthenticatedTestHubRoute
  '/test-orchestrator': typeof AuthenticatedTestOrchestratorRoute
  '/visual-tests': typeof AuthenticatedVisualTestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/git': typeof AuthenticatedSettingsGitRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bugs': typeof AuthenticatedBugsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/flow-builder': typeof AuthenticatedFlowBuilderRoute
  '/http-lab': typeof AuthenticatedHttpLabRoute
  '/ide': typeof AuthenticatedIdeRoute
  '/recorder': typeof AuthenticatedRecorderRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/speed-lab': typeof AuthenticatedSpeedLabRoute
  '/test-cases': typeof AuthenticatedTestCasesRoute
  '/test-data': typeof AuthenticatedTestDataRoute
  '/test-hub': typeof AuthenticatedTestHubRoute
  '/test-orchestrator': typeof AuthenticatedTestOrchestratorRoute
  '/visual-tests': typeof AuthenticatedVisualTestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/git': typeof AuthenticatedSettingsGitRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/bugs': typeof AuthenticatedBugsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/flow-builder': typeof AuthenticatedFlowBuilderRoute
  '/_authenticated/http-lab': typeof AuthenticatedHttpLabRoute
  '/_authenticated/ide': typeof AuthenticatedIdeRoute
  '/_authenticated/recorder': typeof AuthenticatedRecorderRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/speed-lab': typeof AuthenticatedSpeedLabRoute
  '/_authenticated/test-cases': typeof AuthenticatedTestCasesRoute
  '/_authenticated/test-data': typeof AuthenticatedTestDataRoute
  '/_authenticated/test-hub': typeof AuthenticatedTestHubRoute
  '/_authenticated/test-orchestrator': typeof AuthenticatedTestOrchestratorRoute
  '/_authenticated/visual-tests': typeof AuthenticatedVisualTestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/git': typeof AuthenticatedSettingsGitRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/bugs'
    | '/dashboard'
    | '/database'
    | '/flow-builder'
    | '/http-lab'
    | '/ide'
    | '/recorder'
    | '/schedules'
    | '/settings'
    | '/speed-lab'
    | '/test-cases'
    | '/test-data'
    | '/test-hub'
    | '/test-orchestrator'
    | '/visual-tests'
    | '/admin/settings'
    | '/admin/users'
    | '/'
    | '/admin/'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/git'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/projects'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bugs'
    | '/dashboard'
    | '/database'
    | '/flow-builder'
    | '/http-lab'
    | '/ide'
    | '/recorder'
    | '/schedules'
    | '/speed-lab'
    | '/test-cases'
    | '/test-data'
    | '/test-hub'
    | '/test-orchestrator'
    | '/visual-tests'
    | '/admin/settings'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/git'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/projects'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/_authenticated/bugs'
    | '/_authenticated/dashboard'
    | '/_authenticated/database'
    | '/_authenticated/flow-builder'
    | '/_authenticated/http-lab'
    | '/_authenticated/ide'
    | '/_authenticated/recorder'
    | '/_authenticated/schedules'
    | '/_authenticated/settings'
    | '/_authenticated/speed-lab'
    | '/_authenticated/test-cases'
    | '/_authenticated/test-data'
    | '/_authenticated/test-hub'
    | '/_authenticated/test-orchestrator'
    | '/_authenticated/visual-tests'
    | '/admin/settings'
    | '/admin/users'
    | '/_authenticated/'
    | '/admin/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/git'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/projects'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/visual-tests': {
      id: '/_authenticated/visual-tests'
      path: '/visual-tests'
      fullPath: '/visual-tests'
      preLoaderRoute: typeof AuthenticatedVisualTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-orchestrator': {
      id: '/_authenticated/test-orchestrator'
      path: '/test-orchestrator'
      fullPath: '/test-orchestrator'
      preLoaderRoute: typeof AuthenticatedTestOrchestratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-hub': {
      id: '/_authenticated/test-hub'
      path: '/test-hub'
      fullPath: '/test-hub'
      preLoaderRoute: typeof AuthenticatedTestHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-data': {
      id: '/_authenticated/test-data'
      path: '/test-data'
      fullPath: '/test-data'
      preLoaderRoute: typeof AuthenticatedTestDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-cases': {
      id: '/_authenticated/test-cases'
      path: '/test-cases'
      fullPath: '/test-cases'
      preLoaderRoute: typeof AuthenticatedTestCasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/speed-lab': {
      id: '/_authenticated/speed-lab'
      path: '/speed-lab'
      fullPath: '/speed-lab'
      preLoaderRoute: typeof AuthenticatedSpeedLabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recorder': {
      id: '/_authenticated/recorder'
      path: '/recorder'
      fullPath: '/recorder'
      preLoaderRoute: typeof AuthenticatedRecorderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ide': {
      id: '/_authenticated/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof AuthenticatedIdeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/http-lab': {
      id: '/_authenticated/http-lab'
      path: '/http-lab'
      fullPath: '/http-lab'
      preLoaderRoute: typeof AuthenticatedHttpLabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flow-builder': {
      id: '/_authenticated/flow-builder'
      path: '/flow-builder'
      fullPath: '/flow-builder'
      preLoaderRoute: typeof AuthenticatedFlowBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bugs': {
      id: '/_authenticated/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof AuthenticatedBugsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/projects': {
      id: '/_authenticated/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AuthenticatedSettingsProjectsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/git': {
      id: '/_authenticated/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof AuthenticatedSettingsGitRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsGitRoute: typeof AuthenticatedSettingsGitRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsProjectsRoute: typeof AuthenticatedSettingsProjectsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
  AuthenticatedSettingsGitRoute: AuthenticatedSettingsGitRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsProjectsRoute: AuthenticatedSettingsProjectsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBugsRoute: typeof AuthenticatedBugsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedFlowBuilderRoute: typeof AuthenticatedFlowBuilderRoute
  AuthenticatedHttpLabRoute: typeof AuthenticatedHttpLabRoute
  AuthenticatedIdeRoute: typeof AuthenticatedIdeRoute
  AuthenticatedRecorderRoute: typeof AuthenticatedRecorderRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSpeedLabRoute: typeof AuthenticatedSpeedLabRoute
  AuthenticatedTestCasesRoute: typeof AuthenticatedTestCasesRoute
  AuthenticatedTestDataRoute: typeof AuthenticatedTestDataRoute
  AuthenticatedTestHubRoute: typeof AuthenticatedTestHubRoute
  AuthenticatedTestOrchestratorRoute: typeof AuthenticatedTestOrchestratorRoute
  AuthenticatedVisualTestsRoute: typeof AuthenticatedVisualTestsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBugsRoute: AuthenticatedBugsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedFlowBuilderRoute: AuthenticatedFlowBuilderRoute,
  AuthenticatedHttpLabRoute: AuthenticatedHttpLabRoute,
  AuthenticatedIdeRoute: AuthenticatedIdeRoute,
  AuthenticatedRecorderRoute: AuthenticatedRecorderRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSpeedLabRoute: AuthenticatedSpeedLabRoute,
  AuthenticatedTestCasesRoute: AuthenticatedTestCasesRoute,
  AuthenticatedTestDataRoute: AuthenticatedTestDataRoute,
  AuthenticatedTestHubRoute: AuthenticatedTestHubRoute,
  AuthenticatedTestOrchestratorRoute: AuthenticatedTestOrchestratorRoute,
  AuthenticatedVisualTestsRoute: AuthenticatedVisualTestsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
